### ISSUE TITLE
Redirection to libcgi.com

### ISSUE THREAD

**Issue by Ojtulek** [barrosbleo/Pokemon-Global#160]
Hi, i try to install your repo at my xampp. But after install it and configuration databse page always redirect me from my localhost ro libcgi.com/pkm why ??

**Comment by barrosbleo** [comment]
Hi bro.
Actualy this repo is not public... I just set it to public for testing rsrs.
but, if you'd like to see the files running i can install and set it online in a host.

This is a game very similar to the old fire red and leaf green games, but its a mmorpg, you can see players online and battle them, you could also catch pokemon by hunting them... its very cool, but it still lacking maps...

I would like to keep the game online and make money with it, but I work alone on it. It'd be great if you are interested on making a team.

**Comment by barrosbleo** [comment]
> Hi, i try to install your repo at my xampp. But after install it and configuration databse page always redirect me from my localhost ro libcgi.com/pkm why ??

send me a mail if you'd like to make a collab: barrosbleo@gmail.com or contact@lbcgi.com

**Comment by barrosbleo** [comment]
you missconfigured it. Checkout .htaccess and configuration files.
